apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: sredb
            - name: POSTGRES_USER
              value: sreuser
            - name: POSTGRES_PASSWORD
              value: srepass
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sre-demo
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
